import { Opportunity } from '@/types';

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Software Engineering Intern',
    company: 'Google',
    description: 'Summer 2025 internship opportunity for Software Engineering. Work on cutting-edge projects with world-class engineers. Requirements: CS major, strong coding skills in Python/Java/C++, 3.0+ GPA.',
    opportunity_type: 'internship',
    application_deadline: '2024-11-01',
    contact_email: 'university-recruiting@google.com',
    application_url: 'https://careers.google.com/jobs',
    salary_range: '$7,000 - $9,000/month',
    location: 'Mountain View, CA',
    posted_by: '4',
    status: 'active',
    created_at: '2024-09-01T00:00:00Z'
  },
  {
    id: '2',
    title: 'Data Analyst Co-op',
    company: 'Amazon',
    description: '6-month co-op starting Spring 2025. Analyze large datasets, create visualizations, and drive data-driven decisions. Perfect for Business Analytics or Statistics majors.',
    opportunity_type: 'co-op',
    application_deadline: '2024-10-15',
    contact_email: 'university@amazon.com',
    application_url: 'https://amazon.jobs',
    salary_range: '$30-35/hour',
    location: 'Seattle, WA (Remote available)',
    posted_by: '1',
    status: 'active',
    created_at: '2024-08-28T00:00:00Z'
  },
  {
    id: '3',
    title: 'Marketing Intern',
    company: 'Meta',
    description: 'Join Meta\'s marketing team for Summer 2025! Work on social media campaigns, market research, and product launches. Open to Marketing, Communications, or Business majors.',
    opportunity_type: 'internship',
    application_deadline: '2024-10-30',
    contact_email: 'recruiting@meta.com',
    application_url: 'https://metacareers.com',
    salary_range: '$6,500 - $8,500/month',
    location: 'Menlo Park, CA',
    posted_by: '2',
    status: 'active',
    created_at: '2024-09-05T00:00:00Z'
  },
  {
    id: '4',
    title: 'Financial Analyst',
    company: 'Goldman Sachs',
    description: 'Full-time Financial Analyst position starting July 2025. Work with investment banking teams on financial modeling, valuations, and client presentations. Finance or Economics majors preferred.',
    opportunity_type: 'job',
    application_deadline: '2024-11-15',
    contact_email: 'campus@gs.com',
    application_url: 'https://goldmansachs.com/careers',
    salary_range: '$95,000 - $110,000/year',
    location: 'New York, NY',
    posted_by: '4',
    status: 'active',
    created_at: '2024-08-20T00:00:00Z'
  },
  {
    id: '5',
    title: 'UX Design Intern',
    company: 'Apple',
    description: 'Summer 2025 UX Design internship. Design intuitive user interfaces for Apple products. Must have portfolio showcasing design work. Figma and Sketch experience required.',
    opportunity_type: 'internship',
    application_deadline: '2024-10-20',
    contact_email: 'college@apple.com',
    application_url: 'https://apple.com/careers',
    salary_range: '$8,000 - $10,000/month',
    location: 'Cupertino, CA',
    posted_by: '2',
    status: 'active',
    created_at: '2024-09-10T00:00:00Z'
  },
  {
    id: '6',
    title: 'Consulting Analyst Intern',
    company: 'McKinsey & Company',
    description: 'Summer internship with McKinsey. Work on real client projects across various industries. Strong analytical and communication skills required. All majors welcome.',
    opportunity_type: 'internship',
    application_deadline: '2024-10-31',
    contact_email: 'recruiting@mckinsey.com',
    application_url: 'https://mckinsey.com/careers',
    salary_range: '$9,000 - $11,000/month',
    location: 'Multiple locations',
    posted_by: '1',
    status: 'active',
    created_at: '2024-09-02T00:00:00Z'
  },
  {
    id: '7',
    title: 'Research Assistant - AI Lab',
    company: 'University of Florida',
    description: 'Part-time research position in AI/Machine Learning lab. Work on cutting-edge research projects. CS or Engineering majors with Python and ML experience preferred.',
    opportunity_type: 'job',
    contact_email: 'ailab@ufl.edu',
    salary_range: '$15-18/hour',
    location: 'Gainesville, FL (On campus)',
    posted_by: '3',
    status: 'active',
    created_at: '2024-09-12T00:00:00Z'
  },
  {
    id: '8',
    title: 'Mechanical Engineering Co-op',
    company: 'SpaceX',
    description: 'Work on rocket and spacecraft systems. 6-month co-op opportunity starting January 2025. Hands-on experience with manufacturing and testing.',
    opportunity_type: 'co-op',
    application_deadline: '2024-10-10',
    contact_email: 'university@spacex.com',
    application_url: 'https://spacex.com/careers',
    salary_range: '$32-38/hour',
    location: 'Hawthorne, CA',
    posted_by: '2',
    status: 'active',
    created_at: '2024-08-25T00:00:00Z'
  }
];
